### ISSUE TITLE
SSLException: bad_record_mac

### ISSUE THREAD

**Issue by Gamebuster19901** [Gamebuster19901/Roll#9]
This issue is blocking development.

```
java.sql.SQLNonTransientConnectionException: No operations allowed after connection closed.
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:110)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:73)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:73)
	at com.mysql.cj.jdbc.ConnectionImpl.prepareStatement(ConnectionImpl.java:1649)
	at com.gamebuster19901.roll.bot.database.sql.Database.prepareStatement(Database.java:84)
	at com.gamebuster19901.roll.bot.database.Table.selectColumnsFromWhere(Table.java:38)
	at com.gamebuster19901.roll.bot.database.Table.selectColumnsFromWhere(Table.java:49)
	at com.gamebuster19901.roll.bot.database.Table.existsWhere(Table.java:75)
	at com.gamebuster19901.roll.bot.game.character.PlayerCharacter.exists(PlayerCharacter.java:207)
	at com.gamebuster19901.roll.bot.command.argument.StattedArgumentType.lambda$1(StattedArgumentType.java:22)
	at com.mojang.brigadier.tree.ArgumentCommandNode.parse(ArgumentCommandNode.java:59)
	at com.mojang.brigadier.CommandDispatcher.parseNodes(CommandDispatcher.java:365)
	at com.mojang.brigadier.CommandDispatcher.parseNodes(CommandDispatcher.java:392)
	at com.mojang.brigadier.CommandDispatcher.parse(CommandDispatcher.java:348)
	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:176)
	at com.gamebuster19901.roll.bot.command.Dispatcher.execute(Dispatcher.java:15)
	at com.gamebuster19901.roll.bot.command.Dispatcher.execute(Dispatcher.java:1)
	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:142)
	at com.gamebuster19901.roll.bot.command.interaction.Interactions.execute(Interactions.java:68)
	at com.gamebuster19901.roll.bot.EventReceiver$Sub.onStringSelectInteraction(EventReceiver.java:134)
	at net.dv8tion.jda.api.hooks.ListenerAdapter.onEvent(ListenerAdapter.java:424)
	at com.gamebuster19901.roll.bot.EventReceiver.onGenericEvent(EventReceiver.java:67)
	at net.dv8tion.jda.api.hooks.ListenerAdapter.onEvent(ListenerAdapter.java:407)
	at net.dv8tion.jda.api.hooks.InterfacedEventManager.handle(InterfacedEventManager.java:96)
	at net.dv8tion.jda.internal.hooks.EventManagerProxy.handleInternally(EventManagerProxy.java:88)
	at net.dv8tion.jda.internal.hooks.EventManagerProxy.handle(EventManagerProxy.java:70)
	at net.dv8tion.jda.internal.JDAImpl.handleEvent(JDAImpl.java:173)
	at net.dv8tion.jda.internal.handle.InteractionCreateHandler.handleAction(InteractionCreateHandler.java:139)
	at net.dv8tion.jda.internal.handle.InteractionCreateHandler.handleInternally(InteractionCreateHandler.java:86)
	at net.dv8tion.jda.internal.handle.SocketHandler.handle(SocketHandler.java:39)
	at net.dv8tion.jda.internal.requests.WebSocketClient.onDispatch(WebSocketClient.java:965)
	at net.dv8tion.jda.internal.requests.WebSocketClient.onEvent(WebSocketClient.java:851)
	at net.dv8tion.jda.internal.requests.WebSocketClient.handleEvent(WebSocketClient.java:829)
	at net.dv8tion.jda.internal.requests.WebSocketClient.onBinaryMessage(WebSocketClient.java:1004)
	at com.neovisionaries.ws.client.ListenerManager.callOnBinaryMessage(ListenerManager.java:385)
	at com.neovisionaries.ws.client.ReadingThread.callOnBinaryMessage(ReadingThread.java:276)
	at com.neovisionaries.ws.client.ReadingThread.handleBinaryFrame(ReadingThread.java:996)
	at com.neovisionaries.ws.client.ReadingThread.handleFrame(ReadingThread.java:755)
	at com.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:108)
	at com.neovisionaries.ws.client.ReadingThread.runMain(ReadingThread.java:64)
	at com.neovisionaries.ws.client.WebSocketThread.run(WebSocketThread.java:45)
Caused by: com.mysql.cj.exceptions.ConnectionIsClosedException: No operations allowed after connection closed.
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151)
	at com.mysql.cj.NativeSession.checkClosed(NativeSession.java:762)
	at com.mysql.cj.jdbc.ConnectionImpl.checkClosed(ConnectionImpl.java:569)
	at com.mysql.cj.jdbc.ConnectionImpl.prepareStatement(ConnectionImpl.java:1580)
	... 37 more
Caused by: com.mysql.cj.exceptions.CJCommunicationsException: Communications link failure

The last packet successfully received from the server was 9,584 milliseconds ago. The last packet sent successfully to the server was 9,584 milliseconds ago.
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151)
	at com.mysql.cj.exceptions.ExceptionFactory.createCommunicationsException(ExceptionFactory.java:167)
	at com.mysql.cj.protocol.a.NativeProtocol.readMessage(NativeProtocol.java:520)
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:700)
	at com.mysql.cj.protocol.a.NativeProtocol.sendCommand(NativeProtocol.java:639)
	at com.mysql.cj.protocol.a.NativeProtocol.sendQueryPacket(NativeProtocol.java:987)
	at com.mysql.cj.NativeSession.execSQL(NativeSession.java:666)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:930)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeQuery(ClientPreparedStatement.java:1009)
	at com.gamebuster19901.roll.bot.database.sql.PreparedStatement.query(PreparedStatement.java:287)
	at com.gamebuster19901.roll.bot.database.Table.selectColumnsFromWhere(Table.java:41)
	at com.gamebuster19901.roll.bot.database.Table.selectColumnsFromWhere(Table.java:49)
	at com.gamebuster19901.roll.bot.database.Table.existsWhere(Table.java:75)
	at com.gamebuster19901.roll.bot.EventReceiver.onGenericEvent(EventReceiver.java:49)
	... 19 more
Caused by: javax.net.ssl.SSLException: Received fatal alert: bad_record_mac
	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:133)
	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:117)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:358)
	at java.base/sun.security.ssl.Alert$AlertConsumer.consume(Alert.java:293)
	at java.base/sun.security.ssl.TransportContext.dispatch(TransportContext.java:204)
	at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:172)
	at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1508)
	at java.base/sun.security.ssl.SSLSocketImpl.readApplicationRecord(SSLSocketImpl.java:1479)
	at java.base/sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:1064)
	at java.base/java.io.FilterInputStream.read(FilterInputStream.java:132)
	at com.mysql.cj.protocol.FullReadInputStream.readFully(FullReadInputStream.java:64)
	at com.mysql.cj.protocol.a.SimplePacketReader.readHeaderLocal(SimplePacketReader.java:81)
	at com.mysql.cj.protocol.a.SimplePacketReader.readHeader(SimplePacketReader.java:63)
	at com.mysql.cj.protocol.a.SimplePacketReader.readHeader(SimplePacketReader.java:45)
	at com.mysql.cj.protocol.a.TimeTrackingPacketReader.readHeader(TimeTrackingPacketReader.java:52)
	at com.mysql.cj.protocol.a.TimeTrackingPacketReader.readHeader(TimeTrackingPacketReader.java:41)
	at com.mysql.cj.protocol.a.MultiPacketReader.readHeader(MultiPacketReader.java:54)
	at com.mysql.cj.protocol.a.MultiPacketReader.readHeader(MultiPacketReader.java:44)
	at com.mysql.cj.protocol.a.NativeProtocol.readMessage(NativeProtocol.java:514)
	... 30 more
Attempting to recover from database connection failure...
```

**Comment by Gamebuster19901** [comment]
Probable cause:

```
java.lang.StackOverflowError
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:87)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953)
	at com.mysql.cj.jdbc.ClientPreparedStatement.execute(ClientPreparedStatement.java:371)
	at com.gamebuster19901.roll.bot.database.sql.PreparedStatement.execute(PreparedStatement.java:403)
	at com.gamebuster19901.roll.bot.database.Table.updateWhere(Table.java:85)
	at com.gamebuster19901.roll.bot.game.user.Users.setActiveCharacterInDB(Users.java:90)
	at com.gamebuster19901.roll.bot.game.session.SelfSession.setActiveCharacter(SelfSession.java:108)
	at com.gamebuster19901.roll.bot.game.user.Users.setActiveCharacterInDB(Users.java:95)
	at com.gamebuster19901.roll.bot.game.session.SelfSession.setActiveCharacter(SelfSession.java:108)
	at com.gamebuster19901.roll.bot.game.user.Users.setActiveCharacterInDB(Users.java:95)
	at com.gamebuster19901.roll.bot.game.session.SelfSession.setActiveCharacter(SelfSession.java:108)
	at com.gamebuster19901.roll.bot.game.user.Users.setActiveCharacterInDB(Users.java:95)
	at com.gamebuster19901.roll.bot.game.session.SelfSession.setActiveCharacter(SelfSession.java:108)
	at com.gamebuster19901.roll.bot.game.user.Users.setActiveCharacterInDB(Users.java:95)
	at com.gamebuster19901.roll.bot.game.session.SelfSession.setActiveCharacter(SelfSession.java:108)
	at com.gamebuster19901.roll.bot.game.user.Users.setActiveCharacterInDB(Users.java:95)
	at com.gamebuster19901.roll.bot.game.session.SelfSession.setActiveCharacter(SelfSession.java:108)
	at com.gamebuster19901.roll.bot.game.user.Users.setActiveCharacterInDB(Users.java:95)
	at com.gamebuster19901.roll.bot.game.session.SelfSession.setActiveCharacter(SelfSession.java:108)
	at com.gamebuster19901.roll.bot.game.user.Users.setActiveCharacterInDB(Users.java:95)
```
